oc_platform_home:
    path:     /hello/{page}
    defaults: { _controller: OCPlatformBundle:Publication:index }

oc_platform_add:
    path:     /add
    defaults: { _controller: OCPlatformBundle:Publication:add }
