<?php

namespace OCPlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{

	public function isFlood($ip, $sec)//fonction à completer pour le Flooding
	{
		return false;
	}
}
